name: unify_flutter
description:  An efficient, flexible Flutter-Native hybrid communication framework for seamless module integration and automatic code generation. 
version: 3.0.5
homepage: https://github.com/didi/Unify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.3.0
  analyzer: ^7.4.6
  path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.19.4
